### ISSUE TITLE
Failed to run preprocessor on module 2

### ISSUE THREAD

**Issue by dwr-psandhu** [CADWRDeltaModeling/HelloSCHISM#1]
I am working on Linux with the latest SCHISM (compiled from the github head 
```
schism develop
 git hash 0a8246b
```
I have conda env with schimpy
```
# Name                    Version                   Build  Channel
schimpy                   1.4.2+20.gaed6da7            py_0    cadwr-dms
```

I added the lines as indicated by docs at the top of the input.yaml file and cut and paste into tvd.yaml file as indicated by module 2

I get this error when running the pre-processor
```
Start pre-processing SCHISM inputs...
Processing the top level...
Processing mesh section...
Processing open boundaries...
Filling missing land and island boundaries...
Writing hgrid file...
Creating hgrid.ll file...
/home/azureuser/.conda/envs/schimpy/lib/python3.8/site-packages/pyproj/crs/crs.py:53: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  return _prepare_from_string(" ".join(pjargs))
/home/azureuser/.conda/envs/schimpy/lib/python3.8/site-packages/pyproj/crs/crs.py:294: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  projstring = _prepare_from_string(" ".join((projstring, projkwargs)))
/home/azureuser/.conda/envs/schimpy/lib/python3.8/site-packages/pyproj/crs/crs.py:53: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  return _prepare_from_string(" ".join(pjargs))
/home/azureuser/.conda/envs/schimpy/lib/python3.8/site-packages/pyproj/crs/crs.py:294: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  projstring = _prepare_from_string(" ".join((projstring, projkwargs)))
Processing gr3 outputs...
Creating elev.ic...
Creating temp.ic...
Creating salt.ic...
Creating manning.gr3...
Creating rough.gr3...
Creating diffmin.gr3...
Creating diffmax.gr3...
Creating xlsc.gr3...
Creating windrot_geo2proj.gr3...
Processing prop outputs...
Creating tvd.prop...
/home/azureuser/.conda/envs/schimpy/lib/python3.8/site-packages/schimpy/schism_polygon.py:35: ShapelyDeprecationWarning: Setting custom attributes on geometry objects is deprecated, and will raise an AttributeError in Shapely 2.0
  self._prop = {} if prop is None else prop
Traceback (most recent call last):
  File "/home/azureuser/.conda/envs/schimpy/bin/prepare_schism", line 10, in <module>
    sys.exit(main())
  File "/home/azureuser/.conda/envs/schimpy/lib/python3.8/site-packages/schimpy/prepare_schism.py", line 351, in main
    prepare_schism(args)
  File "/home/azureuser/.conda/envs/schimpy/lib/python3.8/site-packages/schimpy/prepare_schism.py", line 395, in prepare_schism
    update_spatial_inputs(s, inputs, logger)
  File "/home/azureuser/.conda/envs/schimpy/lib/python3.8/site-packages/schimpy/prepare_schism.py", line 298, in update_spatial_inputs
    create_prop_with_polygons(s, inputs, logger)
  File "/home/azureuser/.conda/envs/schimpy/lib/python3.8/site-packages/schimpy/prepare_schism.py", line 219, in create_prop_with_polygons
    s.create_prop_partitioning(fname, polygons, default)
  File "/home/azureuser/.conda/envs/schimpy/lib/python3.8/site-packages/schimpy/schism_setup.py", line 738, in create_prop_partitioning
    attr = self.apply_polygons(polygons, default)
  File "/home/azureuser/.conda/envs/schimpy/lib/python3.8/site-packages/schimpy/schism_setup.py", line 630, in apply_polygons
    expr = compile(expr_str, "fail.txt", "eval")
  File "fail.txt", line 1
    ‘1’
      ^
SyntaxError: invalid character in identifier
```

Maybe an issue with the quotes??

**Comment by dwr-psandhu** [comment]
@lily-tomkovic-DWR  confirmed that the pre-processor can run if I replace the fancy quotes with simple '1'

**Comment by dwr-psandhu** [comment]
Also 
* couple of typos in the m2 documentation as it keeps referring to the m1_preprocessor instead of m2_preprocessor
* code-block shows up , maybe mis formatted rst file
* upwind_t ? I only see upwind_mom = 0 , should I replace that or comment it out ?

**Comment by lily-tomkovic-DWR** [comment]
Fixed majority of issues with commit ccae04b 2/6/23. Still need review of iupwind_t parameter guidance for 5.10 update
